LibreOOPAlgoWeb/Controllers/ApiController.cs
using Newtonsoft.Json;
using LibreOOPWeb.Helpers;
using LibreOOPWeb.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using LibreOOPWeb.Models;
using System.Security.Cryptography;
using System.Text;

namespace LibreOOPWeb.Controllers
{
    public class ApiController : Controller
    {
        //public facing version of checkUploadPermissions
        public async Task<string> verifyToken(string accesstoken)
        {

            await MongoConnection.DeleteExpiredTempEntries();

            if(String.IsNullOrWhiteSpace(accesstoken)) {
                //don't bother stressing the database with an obvious incorrect accesstoken
                return "unknown";
            }

            var salt = Config.NsHost + "verifyToken";

            var crypt = new System.Security.Cryptography.SHA256Managed();
            var hash = new System.Text.StringBuilder();
            byte[] crypto = crypt.ComputeHash(Encoding.UTF8.GetBytes(salt+accesstoken));
            foreach (byte theByte in crypto)
            {
                hash.Append(theByte.ToString("x2"));
            }
            var temp =hash.ToString();

            await MongoConnection.AsyncInsertTempPassword(temp);

            var nonExpiredDuplicates = await MongoConnection.countNonExpiredTempEntries(temp);

            //more than x number of attempts the last couple of hours, prevent abuse, display unknown
            if (nonExpiredDuplicates > 5) {
                return "unknown";
            }


            var isValid =  await NightscoutPermissions.CheckUploadPermissions(accesstoken);

            return isValid ? "valid" : "unknown";
        }

        private async Task<bool> checkUploadPermissions(string accesstoken){
            //return true;
            return await NightscoutPermissions.CheckUploadPermissions(accesstoken);
        }

        private async Task<bool> checkProcessingPermissions(string process_token){
            //return true;
            return await NightscoutPermissions.CheckProcessPermissions(process_token);
        }

        private ActionResult Error(string msg){
            return Json(
                new
                {
                    Error = true,
                    Message = msg
                },
                JsonRequestBehavior.AllowGet);
        } 
        private ActionResult Success<T>(T result, string command){
            return Json(
                new
                {
                    Error = false,
                    Command = command,
                    Result = result
                },
                JsonRequestBehavior.AllowGet);
        } 
        public async Task<ActionResult> DeleteTestReadings(string processing_accesstoken){
            if (!await this.checkProcessingPermissions(processing_accesstoken))
            {
                return this.Error("DeleteTestReadings Denied");
            }

            try
            {
                await MongoConnection.DeleteTestReadings();
            } catch(Exception ex) {
                return this.Error("DeleteTestReadings Failed: " + ex.Message);
            }

            return Success<string>("test readings deleted", "DeleteTestReadings");

        }

   

        public async Task<ActionResult> CreateCalibrationRequestAsync(string accesstoken, string b64contents){
            byte[] decoded = null;
            double? footerCRCS = null;

            if (!await this.checkUploadPermissions(accesstoken))
            {
                return this.Error("CreateCalibrationRequestAsync");
            }
            //testing only
            //b64contents = Convert.ToBase64String(LibreUtils.TestPatchAlwaysReturning63);
            //2018-10-07 patch
            //b64contents = "hNtgFwMAAAAAAAAAAAAAAAAAAAAAAAAA+SIECI4EyPRXAKIEyOxXALUEyORXAMgEyNxXADEEyJBYADEEyIBYADEEyGxYADIEyFxYADUEyFBYADoEyEBYAEEEyDRYAEgEyChYAFIEyCBYAF4EyBRYAG4EyAxYAH4EyABYANwEyIhZAEUEyHRZAJoDyExZAEwDyFBZAEsDyMRZAKUDyOwZgLADyAhaADMEyFxYACgFyKRZAC0FyExaAN0EyCQbgKMEyLxZAAQEyPgagK4DyChaAKwDyMRZAAkEyAhZACAEyGRZAOsDyGBZACQEyJhZAPQDyPwagP0DyPBZABMEyLwbgBoEyDgbgK8DyPBbAIkDiOYbgP4DiHJdgL0EyNwbgCIGyNQagLIHyDwagFYHyORZAGoGyMBZACoFyKhZACUGAACWLgABYwddURQHloBaAO2mEHoayATReG4=";
            //2018-08-14 patch
            //b64contents = "p/g4FQMAAAAAAAAAAAAAAAAAAAAAAAAA+4MAAH4DyHRXAn4DyIiXAoMDyJyXAosDyKSXApADyKRXApEDyKyXApkDyLCXAp8DyLiXAqMDyMCXArADyMRXAqwDyMxXAq0DyNSXArEDyLhXAs4DyJyXAtQDyLyXAtsDyMyXAhwEyIzVAvkDyHCWAvADyFAVAwsEyKhWAngDyARXAl0DyBiYAjEDyCyYAh8DyPCWAgwDyHiWAuYCyJiWAuUCyGiWAicDyEjVAisDyFjVAhgDyDjVAhMDyNQUA/QCyHQUA/ACyBjVAtACyCDVAgsDyBQVA8sCyPCWAh8DyKTZATwDyGzaAXEDyCTaAZADyBTaAZ0DyPRXAs4DyNhWAlEDyByXAjwDyFzVAlADyNSVAnADyPhWAkUDyMCWAn4DyHBXAtEwAADISAABBgcYURQHloBaAO2mAG4ayASz2GI=";


            try
            {
                //database expects a base64, which we already have
                // this is just to verify that the contents is valid as base64
                decoded = Convert.FromBase64String(b64contents);

            }
            catch (Exception)
            {
                return this.Error("CreateCalibrationRequestAsync Denied: invalid parameter b64contents: (not a b64string)");
            }



            if (decoded == null || decoded.Count() != LibreUtils.TestPatchAlwaysReturning63.Count())
            {
                return this.Error("CreateCalibrationRequestAsync Denied: Invalid length");
            }




            if (!LibreUtils.verify(decoded))
            {
                return this.Error("CreateCalibrationRequestAsync Denied: Invalid checksums");
            }

            try
            {
                footerCRCS = LibreUtils.CalculateFooterCRCs(decoded);
            }
            catch
            {
                return this.Error("CreateCalibrationRequestAsync Denied: could not extract footer crcs ");

            }
            //modify sensorstatusbyte to a "ready" state
            decoded[4] = 0x03;

            var uuids = new List<String>();
            uuids.Add("b1-cal-" + Guid.NewGuid());
            uuids.Add("b2-cal-" + Guid.NewGuid());
            uuids.Add("f1-cal-" + Guid.NewGuid());
            uuids.Add("f2-cal-" + Guid.NewGuid());
            
            try
            {
                //these calls must not changebody crcs in any way

                var b1 = Convert.ToBase64String(LibreUtils.CreateFakePatch(patch: decoded, raw_glucose: DefaultAlgorithmThresholds.GLUCOSE_LOWER_BOUND, raw_temp: DefaultAlgorithmThresholds.RAW_TEMP1));

                var b2 = Convert.ToBase64String(LibreUtils.CreateFakePatch(patch: decoded, raw_glucose: DefaultAlgorithmThresholds.GLUCOSE_UPPER_BOUND, raw_temp: DefaultAlgorithmThresholds.RAW_TEMP1));

                var f1 = Convert.ToBase64String(LibreUtils.CreateFakePatch(patch: decoded, raw_glucose: DefaultAlgorithmThresholds.GLUCOSE_LOWER_BOUND, raw_temp: DefaultAlgorithmThresholds.RAW_TEMP2));
                var f2 = Convert.ToBase64String(LibreUtils.CreateFakePatch(patch: decoded, raw_glucose: DefaultAlgorithmThresholds.GLUCOSE_UPPER_BOUND, raw_temp: DefaultAlgorithmThresholds.RAW_TEMP2));

                
                await MongoConnection.AsyncInsertReading(new LibreReadingModel { CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now, status = "pending", b64contents = b1, uuid = uuids[0], oldState = null, currentUtcOffset = null, sensorStartTimestamp = null, sensorScanTimestamp = null, newState = null });
                await MongoConnection.AsyncInsertReading(new LibreReadingModel { CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now, status = "pending", b64contents = b2, uuid = uuids[1], oldState = null, currentUtcOffset = null, sensorStartTimestamp = null, sensorScanTimestamp = null, newState = null });
                await MongoConnection.AsyncInsertReading(new LibreReadingModel { CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now, status = "pending", b64contents = f1, uuid = uuids[2], oldState = null, currentUtcOffset = null, sensorStartTimestamp = null, sensorScanTimestamp = null, newState = null });
                await MongoConnection.AsyncInsertReading(new LibreReadingModel { CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now, status = "pending", b64contents = f2, uuid = uuids[3], oldState = null, currentUtcOffset = null, sensorStartTimestamp = null, sensorScanTimestamp = null, newState = null });


            }
            catch (System.TimeoutException)
            {
                return this.Error("CreateCalibrationRequestAsync Failed: Timeout inserting patches to database");
            }
            catch (Exception) {
                return this.Error("CreateCalibrationRequestAsync Failed: Unknown reason");

            }

            LibreCalibrationModel cal;
            try
            {
                var metadata = new AlgorithmMetadata {
                    GLUCOSE_LOWER_BOUND = DefaultAlgorithmThresholds.GLUCOSE_LOWER_BOUND,
                    GLUCOSE_UPPER_BOUND = DefaultAlgorithmThresholds.GLUCOSE_UPPER_BOUND,
                    RAW_TEMP1 = DefaultAlgorithmThresholds.RAW_TEMP1,
                    RAW_TEMP2 = DefaultAlgorithmThresholds.RAW_TEMP2
                };


                cal = new LibreCalibrationModel
                {
                    CreatedOn = DateTime.Now,
                    ModifiedOn = DateTime.Now,
                    uuid = "calibrationmetadata-" + Guid.NewGuid(),
                    metadata = metadata,
                    requestids = uuids,
                    isValidForFooterWithReverseCRCs = LibreUtils.CalculateFooterCRCs(decoded)


                };
                await MongoConnection.AsyncInsertCalibrationReading(cal);

            }
            catch (System.TimeoutException)
            {
                return this.Error("CreateCalibrationRequestAsync Failed: Timeout inserting metadata to database");
            }
            catch (Exception)

LibreOOPAlgoWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using LibreOOPWeb.Utils;
using System.IO;
using System.Globalization;
using System.Web.Hosting;
using LibreOOPWeb.Helpers;
using System.Threading.Tasks;

namespace LibreOOPWeb.Controllers
{
    public class HomeController : Controller
    {
      
        public ActionResult Index()
        {
            //database indexes, run it via mongo shell: 
            //db.librereadings.createIndex({ uuid: 1});
            //db.librereadings.createIndex({ status: 1});
            var mvcName = typeof(Controller).Assembly.GetName();
            var isMono = Type.GetType("Mono.Runtime") != null;

            ViewData["Version"] = mvcName.Version.Major + "." + mvcName.Version.Minor;
            ViewData["Runtime"] = isMono ? "Mono" : ".NET";
            Logger.LogInfo("Accesing Home");
            return View();
        }

        public async Task<ActionResult> CalibrateSensor()
        {
            var shouldNotify = false;
            var secondsOff = 0;
            try
            {
                var d = (await MongoConnection.GetLatestPing()).Value;
                var diff = DateTime.Now - d;
                secondsOff = Convert.ToInt32(diff.TotalSeconds);
                shouldNotify = diff.TotalSeconds > 40;

            }
            catch (InvalidOperationException)
            {


            }
            ViewBag.shouldNotify = shouldNotify;
            ViewBag.secondsOff = secondsOff;

            return View("CalibrateSensor");
        }

        public async Task<ActionResult> UploadRawReading() {
            var shouldNotify = false;
            var secondsOff = 0;
            try
            {
                var d = (await MongoConnection.GetLatestPing()).Value;
                var diff = DateTime.Now - d;
                secondsOff = Convert.ToInt32(diff.TotalSeconds);
                shouldNotify = diff.TotalSeconds > 40;
                
            }
            catch (InvalidOperationException)
            {

                
            }
            ViewBag.shouldNotify = shouldNotify;
            ViewBag.secondsOff = secondsOff;

            return View("UploadRawReading");
        }

        public ActionResult ViewLogs()
        {
            var mvcName = typeof(Controller).Assembly.GetName();
            var isMono = Type.GetType("Mono.Runtime") != null;

            ViewData["Version"] = mvcName.Version.Major + "." + mvcName.Version.Minor;
            ViewData["Runtime"] = isMono ? "Mono" : ".NET";
            Logger.LogInfo("Accesing Logs");
            return View("LogsIndex");
        }

        [HttpPost]
        public ActionResult VerifyViewLog(string logsecret)
        {
            if(logsecret != null && logsecret.Length > 11 && Config.DebugViewLogSecret == logsecret) {
                var today = DateTime.Now.ToString("dddd", CultureInfo.InvariantCulture);
                var logfile = Path.Combine(HostingEnvironment.ApplicationPhysicalPath, "Logs",$"libreoop.log");

                try
                {
                    ViewBag.logdata = System.IO.File.ReadAllText(logfile);
                    return View("LogsIndex");
                } catch (Exception ex) {
                    return Content($"Could not read log file due to exception: {ex}");
                }
            }
            return View("Error");
        }


    }
}

LibreOOPAlgoWeb/Views/Home/CalibrateSensor.cshtml
@using LibreOOPWeb.Helpers;
@{

    ViewBag.Title = "Logs";

}
@if (ViewBag.shouldNotify)
{
<div id="note">
    <strong>Please note!</strong >The processing agent hasn't been online for @ViewBag.secondsOff seconds
</div>
}
<div>
    <h1>Upload raw libre reading</h1>
    <p>
    </p>

    @using (Html.BeginForm("CreateCalibrationRequestAsync", "Api", FormMethod.Post))
    {
        <table>
            <tr>
                <td><label for="accesstoken">Accesstoken:</label> </td>
                <td><input type="text" id="accesstoken" name="accesstoken" size="40" /></td>
            </tr>
            <tr>
                <td><label for="b64contents">Full patch contents ( base64 encoded):</label> </td>
                <td><textarea name="b64contents" id="b64contents" rows="20" cols="100"></textarea></td>
            </tr>
           
        </table>

       
       
        <input type="submit" value="Submit raw reading for processing" />
    }
</div>

<h3>Log:</h3>
<div>
    <textarea rows="5" cols="50" readonly="readonly" id="log"></textarea>
</div>

@section Scripts {
    <script>
    var testdata = "@LibreTestData.TestDataReturns63";
        var $frm = $('form'),
            $log = $('#log'),
            $token = $("#accesstoken"),
            $b64contents = $("#b64contents");
   

var statusurl = "@Url.Action("GetCalibrationStatus", "Api")";


function getStatus(uuid){

    $.ajax({
        type: "POST",
        url: statusurl,
        data: $.param({accesstoken: $token.val(), uuid: uuid}),
        success: function (data) {
            
            if (data.Error) {
                loghelper("Error: " + data.Message);
            } else if (data.Result && data.Result.status && data.Result.status == "complete") {
                loghelper(JSON.stringify(data.Result));
                clearTimers();
            } else if (data.Result && data.Result.uuid) {
                updateLog(data.Result);
            }
        },
        error: function (data) {
            loghelper("There was a problem, check the console!");
            console.log("Problem:");
            console.log(data);
        },
    });
}

function updateLog(res){
    console.log("hit updatelog")
    

    //var updatedAt =  timestring2Date(res.ModifiedOn);
    var uuid = res.uuid;

    if (uuid ) {
        loghelper("Got uuid " + uuid + ", setting  timer to check status in 5 seconds");
        clearTimers();
        setupTimer(uuid);
    }

}
var timers = [];

function clearTimers() {
  for(var timer in timers) {
    if(timers.hasOwnProperty(timer)){
     window.clearInterval(timer);
    }
  }
  timers = [];
}

function timestring2Date(astr) {
    return new Date(parseInt(astr.replace(/[^\d.]/g, ''), 10));
        }

function setupTimer(uuid) {

    timers.push(window.setTimeout(function(){
        console.log("interval reached, uuid:" + uuid);
        getStatus(uuid);
    }, 5000));
}

function loghelper(msg){
  var now = new Date().toLocaleTimeString();
  $log.val($log.val() + "\n[" + now + "] " + msg)
  .scrollTop($log[0].scrollHeight);
}

$frm.submit(function (e) {

    e.preventDefault();

    loghelper("Submitting");
    $.ajax({
        type: $frm.attr('method'),
        url: $frm.attr('action'),
        data: $frm.serialize(),
        success: function (data) {
            if(data.Error){
                alert("There was a problem with your request: " + data.Message);
            } else if(data.Result){
                updateLog(data.Result);
            }
        },
        error: function (data) {
            loghelper("There was a problem, check the console!");
            console.log("Problem:");
            console.log(data);
        },
    });
});

// popup for example data


$b64contents.data('powertipjq', $(
    "<p><strong>Don't know what to write here?</strong></p>" +
    '<p><button class="inserttestdata">Insert Testdata</button> or<a href="https://www.base64decode.org/"> click here</a></p>' +
    '<p><a href="https://www.base64decode.org/">to learn how to encode your data to b64</a></p>'
))
.powerTip({
    placement: 'e',
    mouseOnToPopup: true
});


    
$(document.body).on("mousedown", "button.inserttestdata",function(e){
    $b64contents.val(testdata);
    console.log("b64contents to be filled");
    e.preventDefault();
})



    </script>
}

LibreOOPAlgoWeb/Views/Home/LogsIndex.cshtml
@{
    
    ViewBag.Title = "Logs";

}

<div>
    <h1>Logs</h1>
    <p>This is a custom server that behaves like a Dexcom Share server, but will fetch its glucose values from nightscout</p>
    <p>To view todays logs, please define an environment variable (app setting in azure) called Log_Secret and use a value of at least 12 characters</p>
    <p>
       You must match that secret in the form below to be able to view logs
    </p>

   @using (Html.BeginForm("VerifyViewLog", "Home", FormMethod.Post))
{
    <input type="password" name="logsecret" />

    <input type="submit" value="Submit to view logs" />
}

</div>

@if (ViewBag.logdata != null) {
 <h2>logdata</h2>
 <pre>@ViewBag.logdata</pre>
}

@section Scripts {
    <script>
      
    </script>
}

LibreOOPAlgoWeb/Views/Home/UploadRawReading.cshtml
@using LibreOOPWeb.Helpers;
@{

    ViewBag.Title = "Logs";

}
@if (ViewBag.shouldNotify)
{
<div id="note">
    <strong>Please note!</strong >The processing agent hasn't been online for @ViewBag.secondsOff seconds
</div>
}
<div>
    <h1>Upload raw libre reading</h1>
    <p>
    </p>

    @using (Html.BeginForm("CreateRequestAsync", "Api", FormMethod.Post))
    {
        <table>
            <tr>
                <td><label for="accesstoken">Accesstoken:</label> </td>
                <td><input type="text" id="accesstoken" name="accesstoken" size="40" /></td>
            </tr>
            <tr>
                <td><label for="b64contents">Full patch contents ( base64 encoded):</label> </td>
                <td><textarea name="b64contents" id="b64contents" rows="20" cols="100"></textarea></td>
            </tr>
            <tr>
                <td>Current BG:</td>
                <td id="currentbg" class="notavailable">NOT_AVAILABLE</td>
            </tr>
            <tr>
                <td>Generated newState</td>
                <td id="newState" class="notavailable">NOT_AVAILABLE</td>
            </tr>
        </table>

        <h3 id="showhideadvanced">Advanced options (can be blank)</h3>
        <table id="tableadvanced">
            <tr>
                <td><label for="oldState">oldstate ( base64 encoded):</label></td>
                <td><input type="text" name="oldState" id="oldState" size="60" /></td>

            </tr>
             <tr>
                <td><label for="sensorStartTimestamp">sensorStartTimestamp:</label></td>
                <td><input type="text" name="sensorStartTimestamp" id="sensorStartTimestamp" size="40" /></td>

            </tr>
            <tr>
                <td><label for="sensorScanTimestamp">sensorScanTimestamp:</label></td>
                <td><input type="text" name="sensorScanTimestamp" id="sensorScanTimestamp" size="40" /></td>

            </tr>
            <tr>
                <td><label for="currentUtcOffset">currentUtcOffset:</label></td>
                <td><input type="text" name="currentUtcOffset" id="currentUtcOffset" size="40" /></td>

            </tr>
        
        </table>
       
        <input type="submit" value="Submit raw reading for processing" />
    }
</div>

<h3>Log:</h3>
<div>
    <textarea rows="5" cols="50" readonly="readonly" id="log"></textarea>
</div>

@section Scripts {
    <script>
var testdata = "@LibreTestData.TestDataReturns63";
var testdataStartTime = @LibreTestData.TestDataReturns63SensorStartTimestamp;
var testdataScanTime = @LibreTestData.TestDataReturns63SensorScanTimestamp;
var testdataOffset = @LibreTestData.TestDataReturns63CurrentUtcOffset;
    
var $frm = $('form'),
    $log = $('#log'),
    $token =$("#accesstoken"),
    $currentbg = $("#currentbg"),
    $b64contents = $("#b64contents"),
    $oldState = $("#oldState"),
    $start = $("#sensorStartTimestamp"),
    $scan = $("#sensorScanTimestamp"),
    $offset = $("#currentUtcOffset")
    $newState = $("#newState");

var statusurl = "@Url.Action("GetStatus", "Api")";

function precisionRound(number, precision) {
  var factor = Math.pow(10, precision);
  return Math.round(number * factor) / factor;
}

function timestring2Date(astr) {
    return new Date(parseInt(astr.replace (/[^\d.]/g, '' ), 10));
}

function getStatus(uuid){

    $.ajax({
        type: "POST",
        url: statusurl,
        data: $.param({accesstoken: $token.val(), uuid: uuid}),
        success: function (data) {

            if(data.Error){
                loghelper("Error: " + data.Message);
            } else if(data.Result){
                updateLog(data.Result);

            }
        },
        error: function (data) {
            loghelper("There was a problem, check the console!");
            console.log("Problem:");
            console.log(data);
        },
    });
}

function updateLog(res){

    var updatedAt =  timestring2Date(res.ModifiedOn);
    var result = res.result;
    var uuid = res.uuid;
    var newState = res.newState;

    if (result) {
        loghelper("BG generated at " + updatedAt + ": " + result + " mgdl");
        try{
            console.log("result:" + result);
            var matches = result.match(/currentbg: (-?\d+)/i)
          var mgdl = parseInt(matches[1], 10);
          var mmol = precisionRound(mgdl / 18, 1);
          var extra = "";
          if (mgdl <= 0) {
              extra = " ( INVALID??) ";
          }
          $currentbg.removeClass("notavailable available").addClass(mgdl <= 0 ? "notavailable" : "available")
          .html(mgdl + " mgdl / " + mmol + " mmol " + extra);

          $newState.removeClass("notavailable available")
            .addClass(newState && newState.length >0 ?  "available" : "notavailable" )
            .html(newState && newState.length >0 ? newState : "");
          console.log("got newstate:" + newState);
    
        } catch(err){}
    }

    if (result === null && uuid ) {
        loghelper("Got uuid " + uuid + ", setting  timer to check status in 5 seconds");
        clearTimers();
        setupTimer(uuid);
    }

}
var timers = [];

function clearTimers() {
  for(var timer in timers) {
    if(timers.hasOwnProperty(timer)){
     window.clearInterval(timer);
    }
  }
  timers = [];
}

function setupTimer(uuid) {

    timers.push(window.setTimeout(function(){
        console.log("interval reached, uuid:" + uuid);
        getStatus(uuid);
    }, 5000));
}

function loghelper(msg){
  var now = new Date().toLocaleTimeString();
  $log.val($log.val() + "\n[" + now + "] " + msg)
  .scrollTop($log[0].scrollHeight);
}

$frm.submit(function (e) {

    e.preventDefault();

    loghelper("Submitting");
    $.ajax({
        type: $frm.attr('method'),
        url: $frm.attr('action'),
        data: $frm.serialize(),
        success: function (data) {
            if(data.Error){
                alert("There was a problem with your request: " + data.Message);
            } else if(data.Result){
                updateLog(data.Result);
            }
        },
        error: function (data) {
            loghelper("There was a problem, check the console!");
            console.log("Problem:");
            console.log(data);
        },
    });
});

// popup for example data


$b64contents.data('powertipjq', $(
    "<p><strong>Don't know what to write here?</strong></p>" +
    '<p><button class="inserttestdata">Insert Testdata</button> or<a href="https://www.base64decode.org/"> click here</a></p>' +
    '<p><a href="https://www.base64decode.org/">to learn how to encode your data to b64</a></p>'
))
.powerTip({
    placement: 'e',
    mouseOnToPopup: true
});

$oldState.data('powertipjq', $(
    "<p><strong>Don't know what to write here?</strong></p>" +
    '<p>If specified, the oldstate should be the newstate from a previous reading</p>' 
))
.powerTip({
    placement: 'e',
    mouseOnToPopup: true
});

$start.data('powertipjq', $(
    "<p><strong>Don't know what to write here?</strong></p>" +
    '<p><button class="insertstarttimestamp">Insert Testdata</button>' 
))
.powerTip({
    placement: 'e',
    mouseOnToPopup: true
});

$scan.data('powertipjq', $(
    "<p><strong>Don't know what to write here?</strong></p>" +
    '<p><button class="insertscantimestamp">Insert Testdata</button>' 
))
.powerTip({
    placement: 'e',
    mouseOnToPopup: true
});

$offset.data('powertipjq', $(
    "<p><strong>Don't know what to write here?</strong></p>" +
    '<p><button class="insertoffsettimestamp">Insert Testdata</button>' 
))
.powerTip({
    placement: 'e',
    mouseOnToPopup: true
});  
    

    
$(document.body).on("mousedown", "button.inserttestdata",function(e){
    $b64contents.val(testdata);
    console.log("b64contents to be filled");
    e.preventDefault();
})
.on("mousedown", "button.insertstarttimestamp",function(e){
    $start.val(testdataStartTime);
    e.preventDefault();
})
.on("mousedown", "button.insertscantimestamp",function(e){
    $scan.val(testdataScanTime);
    e.preventDefault();
})
.on("mousedown", "button.insertoffsettimestamp",function(e){
    $offset.val(testdataOffset);
    e.preventDefault();
})


    </script>
}